trigger:
 branches:
    include:
      - main


variables:
  buildconfiguration: 'RELEASE'


STAGES:

#========ci sTAGE=========


- stage: build
  displayName: 'build stage'
  jobs:
  - job: buildjob
    pool:
      vmimage: 'ubuntu-latest'
    steps:
    - task: useDotNet@2
      inputs:
        packageType: 'sdk'
        version: '7.x.x'
        installationpath: $(Agent.ToolsDirectory)/dotnet


    - task: DotnetCoreClI@2
      displayName: 'restore Dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'



    - task: DotNetCoreCLI@2
      displayName: 'Build App'
      inputs:
       command: 'Build' 
       projects: '**/*.csproj'
       arguments: '--configuration $(buildconfiguration)'



    - task: DotNetCoreCLI@2
      displayName: 'run Unit tests'
      inputs:
        command: 'test'  
        Projects: '**/*.csproj'


    - task: publishBuildArtifacts@1
      inputs:
        pathtopublish: '$(Build.ArtifactsstagingDirectory)'
        ArtifactName: 'drop' 
        publishLocation: 'container' 



        #========CD Stage -QA Deployment=========


- stage: deployQA
  displayName: 'Deploy to QA'
  dependsOn: build
  Conditon: succeeded()
  jobs: 
   - deployment: QADeployment
     environment: 'QA'
     strategy:
        runOnce:
          deploy: 
            steps:
            - task: AzureWebApp@1
              inputs:
                azuresubscription: 'azureSp-prod'
                appName: 'fintechapp-prod'
                package: '$(pipeline.workspace)/drop/**/*.zip'




                #========cD stage - prod Deployment with Manuual Approval=========

- stage: Deployprod
  displayName: 'Deploy to production'
  dependson: deployQA
  condition: succeeded()
  approval:
    approvals:
      - reviewers:
         - name: 'manoj,valvi@gmail.com'


  jobs:
  - deployment: prodDeployment
    environment: 'production'
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azuresubscription: 'azureSp-prod'
              appName: 'fintechapp-prod'
              package: '$(pipeline.workspace)./drop/**/*.zip'     

        


          